// Generated by gencpp from file elfin_robot_msgs/SetFloat64s.msg
// DO NOT EDIT!


#ifndef ELFIN_ROBOT_MSGS_MESSAGE_SETFLOAT64S_H
#define ELFIN_ROBOT_MSGS_MESSAGE_SETFLOAT64S_H

#include <ros/service_traits.h>


#include <elfin_robot_msgs/SetFloat64sRequest.h>
#include <elfin_robot_msgs/SetFloat64sResponse.h>


namespace elfin_robot_msgs
{

struct SetFloat64s
{

typedef SetFloat64sRequest Request;
typedef SetFloat64sResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFloat64s
} // namespace elfin_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::elfin_robot_msgs::SetFloat64s > {
  static const char* value()
  {
    return "5739026f6f0517440e663ba60441de94";
  }

  static const char* value(const ::elfin_robot_msgs::SetFloat64s&) { return value(); }
};

template<>
struct DataType< ::elfin_robot_msgs::SetFloat64s > {
  static const char* value()
  {
    return "elfin_robot_msgs/SetFloat64s";
  }

  static const char* value(const ::elfin_robot_msgs::SetFloat64s&) { return value(); }
};


// service_traits::MD5Sum< ::elfin_robot_msgs::SetFloat64sRequest> should match 
// service_traits::MD5Sum< ::elfin_robot_msgs::SetFloat64s > 
template<>
struct MD5Sum< ::elfin_robot_msgs::SetFloat64sRequest>
{
  static const char* value()
  {
    return MD5Sum< ::elfin_robot_msgs::SetFloat64s >::value();
  }
  static const char* value(const ::elfin_robot_msgs::SetFloat64sRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::elfin_robot_msgs::SetFloat64sRequest> should match 
// service_traits::DataType< ::elfin_robot_msgs::SetFloat64s > 
template<>
struct DataType< ::elfin_robot_msgs::SetFloat64sRequest>
{
  static const char* value()
  {
    return DataType< ::elfin_robot_msgs::SetFloat64s >::value();
  }
  static const char* value(const ::elfin_robot_msgs::SetFloat64sRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::elfin_robot_msgs::SetFloat64sResponse> should match 
// service_traits::MD5Sum< ::elfin_robot_msgs::SetFloat64s > 
template<>
struct MD5Sum< ::elfin_robot_msgs::SetFloat64sResponse>
{
  static const char* value()
  {
    return MD5Sum< ::elfin_robot_msgs::SetFloat64s >::value();
  }
  static const char* value(const ::elfin_robot_msgs::SetFloat64sResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::elfin_robot_msgs::SetFloat64sResponse> should match 
// service_traits::DataType< ::elfin_robot_msgs::SetFloat64s > 
template<>
struct DataType< ::elfin_robot_msgs::SetFloat64sResponse>
{
  static const char* value()
  {
    return DataType< ::elfin_robot_msgs::SetFloat64s >::value();
  }
  static const char* value(const ::elfin_robot_msgs::SetFloat64sResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ELFIN_ROBOT_MSGS_MESSAGE_SETFLOAT64S_H
